version: 2
jobs:
  build:
    docker:
      - image: python:2.7
    working_directory: /home/lmswebaula/
    steps:
      - checkout
      - run:
          name: Create test folders
          command: |
            mkdir -p /home/lmswebaula/reports/coverage
      - run:
          name: Install package
          command: |
            python /home/lmswebaula/setup.py develop
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
      - run:
          name: Install Requirements
          command: |
            pip install -r requirements-dev.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - "/home/lmswebaula/.pip-cache"
      - run:
          name: Run tests
          command: |
            pytest --cov-config /home/lmswebaula/.coveragerc --cov-report html --cov=lms /home/lmswebaula/tests/
      - run:
          name: Update Code Coverage
          command: |
            mkdir -p /home/lmswebaula/html_cov
            coverage html -d html_cov
      - store_artifacts:
          path: "/home/lmswebaula/html_cov"
      - store_artifacts:
          path: "/home/lmswebaula/.coverage"
      - store_test_results:
          path: "/home/lmswebaula/html_cov"

